name = "JPerluxo Modpack"
author = "JPerluxo"
version = "1.1.0"
description = "The definitive, lightweight environment to experience the JPerluxo Mod."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e9ea9f51c5fed8889007d63178b70ec6787ba3686f140ec0edbd63cf48b9a18"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
