name = "JPerluxo Modpack"
author = "JPerluxo"
version = "1.0.0"
description = "The definitive, lightweight environment to experience the JPerluxo Mod."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f40a741f99c08b5ede0f784794389a6bd34ad36c3824609b52742ab87c11e6d0"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
